### ISSUE TITLE
Cannot upload media

### ISSUE THREAD

**Issue by LaceyWilson** [PressForward/pressforward-turnkey-theme#68]
I get this message when trying to upload images "Unable to create directory wp-content/uploads/2015/11. Is its parent directory writable by the server?"

**Comment by aodiorne** [comment]
This is because the folder has fellows as the owner/group (524) and it should be chnmdev (501).  I think I know how to change it, but feel a bit rusty with the shell, so maybe we should ask Roberto to change the folder ownership.  The image uploads work fine on another site I used.

**Comment by aodiorne** [comment]
I think this is because the folder owner/group is fellows (524) and the owner needs to be the same as the www folder chnmdev (501).  I think I know how to change it, but feel a little rusty with shell commands, so maybe we can ask Roberto to change the folder ownership.  I uploaded images okay on another site that I set up.

**Comment by regan008** [comment]
@aodiorne Yes lets not change permissions on the server.  @LaceyWilson lets
ignore this issue for now. I'll go back and fix it when I begin refactoring.
